config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :recipes do
    resources :comments
  end

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  # the author_name must be provided
  validates :author_name, presence: { message: "Must be provided please" }, allow_blank: false
  validates :body, length: { minimum: 3, too_short: "Comment must be at least 3 characters long."}
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients, dependent: :delete_all
	has_many :directions, dependent: :delete_all
	has_many :comments, dependent: :delete_all
	belongs_to :user
	has_attached_file :image, styles: {  :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	accepts_nested_attributes_for :ingredients,
									reject_if: :all_blank,
									allow_destroy: true
	accepts_nested_attributes_for :directions,
									reject_if: :all_blank,
									allow_destroy: true
	validates :title, :description, :image, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes, dependent: :delete_all

  acts_as_commontator

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  
  def create
    # @comment = Comment.new(comment_params)
    # @comment.recipe_id = params[:recipe_id]
    # @comment.save
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.create(comment_params)


    redirect_to recipe_path(@comment.recipe)
  end


  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/recipes/comments_controller.rb
class Recipes::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Recipe.find(params[:recipe_id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :recipe_auth, only: [:edit, :update, :destroy]

	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
		@comment = @recipe.comments.new
		@comment.recipe_id = @recipe.id

	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.new(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Successfully created new recipe!"
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end


	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy],
			directions_attributes: [:id, :step, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end

	def recipe_auth
		if current_user!=@recipe.user
			redirect_to root_path, notice: "Only the User who created the Recipe can do this."
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_comment.html.haml
.well
  -# %p.strong
  =comment.user.name
  commented
  =simple_format comment.body

app/views/comments/_form.html.haml
%h4 Post a Comment

= simple_form_for [@recipe, @recipe.comments.build], validate: true do |f|
  = f.input :author_name, label: "Your Name"
  = f.input :body, label: "Comment..."
  = f.button :submit

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Recipe Box App
	= csrf_meta_tags
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
	%nav.navbar.navbar-dark{:role => "navigation"}
		.container
			-# .navbar-header
			%button.navbar-toggle{:type => "button",
			:'data-toggle' =>  "collapse",
			:'data-target' =>  "#navbarNav"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			.navbar-brand= link_to "Recipe Box", root_path
			.collapse.navbar-collapse#navbarNav
				- if user_signed_in?
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "New Recipe", new_recipe_path
						%li= link_to "Account", edit_user_registration_path
						%li= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "Sign Up", new_user_registration_path
						%li= link_to "Sign In", new_user_session_path

		.container
			- flash.each do |name, msg|
				= content_tag :div, msg, class: "alert"

			= yield

app/views/recipes/_comment.html.haml
%div#individual_comment
  %h5
    %strong Name:
    = comment.author_name
  %p
    %strong Comment:
    = comment.body

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, label:false, input_html: { class: "form-input form-control" }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= pluralize(@recipe.errors.count, "error")
				prevented this Recipe from saving.
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg

	.panel-body
		= f.input :title, input_html: { class: 'form-control' }				

		= f.input :description, input_html: { class: 'form-control' }

		= f.input :image, as: :file, class: "form-control"

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add ingredient', f, :ingredients, class: "btn btn-default add-button"
			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add direction', f, :directions, class: "btn btn-default add-button"


	= f.button :submit, class: "btn btn-primary"
	= link_to "Cancel", root_path, class: "btn btn-default"

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, label:false, input_html: { class: "form-input form-control" }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/_modal.html.haml
-# Replaces default modal popup for (eg) deleting Pins

.modal.fade{ id: "exampleModal#{@recipe.id}" }
	.modal-sm
		.modal-content
			.modal-header
				%h5.modal-title#exampleModalLabel Delete Confirmation
				%button.close{ "type" => "button", "data-dismiss" => "modal" }
			.modal-body Are you sure?
			.modal-footer
				%button.btn.btn-default{ "type" => "button", "data-dismiss" => "modal" } Cancel
				=link_to 'Delete', @recipe, method: :delete, class: "btn btn-danger"

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
	.row
		- recipes.each do |recipe|
			.col-md-4
				.recipe
					.image_wrapper
						= link_to recipe do
							= image_tag recipe.image.url(:medium)
						%h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

app/views/recipes/show.html.haml
.main-content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.description= @recipe.description
				%p
					Submitted by
					= @recipe.user.email

	.row
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
					- @recipe.ingredients.each do |ingredient|
						%li=ingredient.name

		.col-md-6
			#directions
				%h2 Directions
				%ol
					- @recipe.directions.each do |direction|
						%li= direction.step
	.row
		.col-md-8
			#comments
				%h3 Comments(#{@recipe.comments.size})
				%hr
				= render partial: 'comments/form'
				= render partial: 'recipes/comment', collection: @recipe.comments
	%br/
	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			= link_to "Edit", edit_recipe_path, class: "btn btn-default"
			-# replace with Bootstrap modal cf. pinboard
			%button.btn.btn-danger{"data-target" => "#exampleModal#{@recipe.id}", "data-toggle" => "modal", type: "button"} Delete

			=render 'modal'